name: s390x

on:
  workflow_dispatch: {}   # Allow for manual triggers

jobs:
  generate:
    name: Sync Generated Code and Docs
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate
        shell: bash
        run: |
          # Commit any changes and push as needed.
          SOURCE_ROOT="$(pwd)"
          echo "$SOURCE_ROOT"
          sudo apt-get update
          sudo apt-get install -y curl vim wget git
          sudo apt-get update
          sudo apt-get install -y gcc git make python3 python3-pip tar wget
          cd $HOME
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo dockerd &
          sleep 30
          sudo chmod ugo+rw /var/run/docker.sock
          sudo usermod -aG docker $USER && newgrp docker
          USERNAME=vemef
          PASSWORD=Vemef12345
          docker login -u $USERNAME -p $PASSWORD
          sleep 30
          docker pull golang:1.22.1-bullseye
          # docker pull golang-wasmtime:1.22.4-bullseye
          cd $SOURCE_ROOT
          # See https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          AUTHOR=wasm-updater
          git config user.name ${AUTHOR}
          git config user.email ${AUTHOR}@github.com
          git config --global http.postBuffer 1048576000
          git config --global https.postBuffer 1048576000
          cd $HOME
          GO_VERSION=1.22.1
          wget -q https://storage.googleapis.com/golang/go"${GO_VERSION}".linux-s390x.tar.gz
          chmod ugo+r go"${GO_VERSION}".linux-s390x.tar.gz
          sudo rm -rf /usr/local/go /usr/bin/go
          sudo tar -C /usr/local -xzf go"${GO_VERSION}".linux-s390x.tar.gz
          sudo ln -sf /usr/local/go/bin/go /usr/bin/
          sudo ln -sf /usr/local/go/bin/gofmt /usr/bin/
          sudo ln -sf /usr/bin/gcc /usr/bin/s390x-linux-gnu-gcc  # Rhel and Sles only
          go version
          cd $HOME
          mkdir golang-wasmtime && cd golang-wasmtime
          wget https://github.com/bytecodealliance/wasmtime/releases/download/v3.0.1/wasmtime-v3.0.1-s390x-linux-c-api.tar.xz
          tar xf wasmtime-v3.0.1-s390x-linux-c-api.tar.xz
          sudo cp wasmtime-v3.0.1-s390x-linux-c-api/lib/libwasmtime.a /usr/lib
          
          # Build toolchain image
          wget https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/OPA/0.63.0/patch/golang-wasmtime.Dockerfile
          
          sudo docker build -t golang-wasmtime:1.22.4-bullseye -f ./golang-wasmtime.Dockerfile .
          cd $HOME
          wget https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/OPA/0.63.0/patch/opa.diff
          cd $SOURCE_ROOT

  Build:
    name: Release Build 
    runs-on: self-hosted
    needs: generate
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Linux s390x
        run: |
          git apply $HOME/opa.diff
          git diff
          make ci-go-ci-build-linux

  Test:
    name: Test on s390x
    runs-on: self-hosted
    needs: [Build]
    steps:
      - name: Build Linux s390x
        run: |
          make image-s390x
          make test

